openapi: 3.0.1
info:
  title: Nivtron SmartMoney API
  description: Personal Finance & Loan Management API
  version: 1.0.0

tags:
  - name: Auth
    description: Authentication APIs
  - name: User
    description: User profile APIs
  - name: Loan
    description: Loan management APIs
  - name: Strategy
    description: Repayment strategy APIs
  - name: Dashboard
    description: Dashboard APIs

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    BaseResponse:
      $ref: './controller/auth_controller.yaml#/components/schemas/BaseResponse'

paths:
  /auth/register:
    $ref: './controller/auth_controller.yaml#/paths/~1auth~1register'
  /auth/login:
    $ref: './controller/auth_controller.yaml#/paths/~1auth~1login'
  /auth/google:
    $ref: './controller/auth_controller.yaml#/paths/~1auth~1google'
  /users/me:
    $ref: './controller/user_controller.yaml#/paths/~1users~1me'
  /users/me/password:
    $ref: './controller/user_controller.yaml#/paths/~1users~1me~1password'
  /loans:
    $ref: './controller/loan_controller.yaml#/paths/~1loans'
  /loans/strategy/avalanche:
    $ref: './controller/loan_controller.yaml#/paths/~1loans~1strategy~1avalanche'
  /loans/strategy/snowball:
    $ref: './controller/loan_controller.yaml#/paths/~1loans~1strategy~1snowball'
  /loans/{id}:
    $ref: './controller/loan_controller.yaml#/paths/~1loans~1{id}'
  /loans/{id}/simulate:
    $ref: './controller/loan_controller.yaml#/paths/~1loans~1{id}~1simulate'
  /dashboard:
    $ref: './controller/dashboard_controller.yaml#/paths/~1dashboard'
  /calculators/emi:
    $ref: './controller/calculator_controller.yaml#/paths/~1calculators~1emi'
  /calculators/sip:
    $ref: './controller/calculator_controller.yaml#/paths/~1calculators~1sip'
  /calculators/lumpsum:
    $ref: './controller/calculator_controller.yaml#/paths/~1calculators~1lumpsum'