spring.application.name=smartmoney

server.port=9090

# MYSQL DATASOURCE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/nivtron_smartmoney?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

 Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.fail-on-missing-locations=true
spring.flyway.locations=classpath:db/migration

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}

#Google SSO
google.token.info.url=https://oauth2.googleapis.com/tokeninfo?id_token=
google.client.id=34134315010-8bu1cu3grg7k1onhnemj3q0phnbpuvqb.apps.googleusercontent.com

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# Actuator
management.endpoints.web.exposure.include=health,info